spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/nonstopdeploy?autoReconnect=true&serverTimezone=UTC
    username: root
    password: alsdud6038
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true

---
spring:
  profiles: dev
---
spring:
  profiles: real
